const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const contentPath = path.join(root, "content", "desire-packs.json");
const outputPath = path.join(root, "src", "data", "desires.generated.ts");
const validKinds = new Set(["practice", "discussion"]);
const validMoods = new Set(["calme", "sensuel", "aventureux"]);

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    throw new Error(`Impossible de lire ${path.relative(root, filePath)}: ${error.message}`);
  }
}

function assertString(value, label, errors, options = {}) {
  if (typeof value !== "string") {
    errors.push(`${label} doit être un texte.`);
    return "";
  }

  const trimmed = value.trim();
  if (!trimmed && !options.optional) {
    errors.push(`${label} est obligatoire.`);
  }

  if (options.max && trimmed.length > options.max) {
    errors.push(`${label} est trop long (${trimmed.length}/${options.max}).`);
  }

  return trimmed;
}

function slugify(value) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 42);
}

function validateContent(content) {
  const errors = [];

  if (!content || typeof content !== "object") {
    return { errors: ["Le fichier doit contenir un objet JSON."], packs: [] };
  }

  if (!Array.isArray(content.packs)) {
    return { errors: ["La clé packs doit être une liste."], packs: [] };
  }

  const ids = new Set();
  const categories = new Set();
  const packs = content.packs.map((pack, packIndex) => {
    const category = assertString(pack.category, `packs[${packIndex}].category`, errors, { max: 42 });
    if (category === "Perso") {
      errors.push(`packs[${packIndex}].category "Perso" est réservée aux cartes personnalisées.`);
    }
    if (categories.has(category)) {
      errors.push(`packs[${packIndex}].category "${category}" existe déjà.`);
    }
    categories.add(category);

    const label = assertString(pack.label ?? category, `packs[${packIndex}].label`, errors, { max: 32 });
    const description = assertString(pack.description ?? "", `packs[${packIndex}].description`, errors, { optional: true, max: 180 });
    const cards = Array.isArray(pack.cards) ? pack.cards : [];

    if (!Array.isArray(pack.cards)) {
      errors.push(`packs[${packIndex}].cards doit être une liste.`);
    }

    return {
      category,
      description,
      label,
      paid: Boolean(pack.paid),
      cards: cards.map((card, cardIndex) => {
        const prefix = `packs[${packIndex}].cards[${cardIndex}]`;
        const title = assertString(card.title, `${prefix}.title`, errors, { max: 58 });
        const emoji = assertString(card.emoji, `${prefix}.emoji`, errors, { max: 8 });
        const blurb = assertString(card.blurb, `${prefix}.blurb`, errors, { max: 140 });
        const id = assertString(card.id || `${slugify(category)}-${String(cardIndex + 1).padStart(2, "0")}`, `${prefix}.id`, errors, {
          max: 72,
        });
        const kind = card.kind || "practice";
        const mood = card.mood || "sensuel";
        const safety = typeof card.safety === "string" ? card.safety.trim() : undefined;

        if (ids.has(id)) {
          errors.push(`${prefix}.id "${id}" existe déjà.`);
        }
        ids.add(id);

        if (!/^[a-z0-9][a-z0-9-]*$/i.test(id)) {
          errors.push(`${prefix}.id "${id}" doit rester stable et ne contenir que lettres, chiffres et tirets.`);
        }

        if (!validKinds.has(kind)) {
          errors.push(`${prefix}.kind "${kind}" n'est pas valide.`);
        }

        if (!validMoods.has(mood)) {
          errors.push(`${prefix}.mood "${mood}" n'est pas valide.`);
        }

        return {
          id,
          title,
          emoji,
          category,
          kind,
          mood,
          blurb,
          ...(safety ? { safety } : {}),
        };
      }),
    };
  });

  return { errors, packs };
}

function toTsString(value) {
  return JSON.stringify(value, null, 2)
    .replace(/"category": "([^"]+)"/g, "\"category\": \"$1\"")
    .replace(/"kind": "([^"]+)"/g, "\"kind\": \"$1\"")
    .replace(/"mood": "([^"]+)"/g, "\"mood\": \"$1\"");
}

function buildOutput(packs) {
  const cards = packs.flatMap((pack) => pack.cards);
  const categories = [...packs.map((pack) => pack.category), "Perso"];
  const metadata = packs.map(({ cards: _cards, ...pack }) => ({
    ...pack,
    cardCount: _cards.length,
  }));

  return `// Generated by scripts/generate-desires.js from content/desire-packs.json.
// Do not edit by hand.

import type { DesireCard, DesireCategory, DesirePack } from "../types";

export const DESIRE_CATEGORIES: DesireCategory[] = ${toTsString(categories)};

export const DESIRE_PACKS: DesirePack[] = ${toTsString(metadata)};

export const desireCards: DesireCard[] = ${toTsString(cards)};
`;
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const content = readJson(contentPath);
  const { errors, packs } = validateContent(content);

  if (errors.length) {
    console.error("Cart content invalide:");
    for (const error of errors) {
      console.error(`- ${error}`);
    }
    process.exit(1);
  }

  const output = buildOutput(packs);

  if (checkOnly) {
    const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
    if (current !== output) {
      console.error("src/data/desires.generated.ts n'est pas à jour. Lance npm run cards:generate.");
      process.exit(1);
    }
    console.log("Card content OK.");
    return;
  }

  fs.writeFileSync(outputPath, output, "utf8");
  console.log(`Generated ${path.relative(root, outputPath)} from ${path.relative(root, contentPath)}.`);
}

main();
